debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["http","https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [entryPoints.https.tls.defaultCertificate]
    certFile = "/certs/cert.crt"
    keyFile = "/certs/cert.key"  
    
